name: cell_detection

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Dependecies
        run:
          python -m pip install --upgrade pip
          pip install pytest flask scikit-learn
          python gen_images.py
